### ISSUE TITLE
Error when uploading file

### ISSUE THREAD

**Issue by simplybenuk** [nhsengland/futurenhs#139]
User has experienced the following problem

"Also had an error when trying to upload a test file:

**An unexpected error occurred when attempting to post the group file**"

**Comment by Alex-Grubba-CDS** [comment]
@simplybenuk do we have repro steps for this scenario and the action the user was trying to perform?

**Comment by simplybenuk** [comment]
I can't seem to recreate this one, is there anything in the logs? Was done sometime on the 3rd May

**Comment by simplybenuk** [comment]
Cannot recreate so closing
