### ISSUE TITLE
Reset password link issue on chrome

### ISSUE THREAD

**Issue by marianthi-design** [nhsengland/futurenhs#150]
When clicking on "forgot password" using Chrome, the reset password email doesn't come through. 2 users experienced this issue (Munsoor and Marianthi).

**Comment by Alex-Grubba-CDS** [comment]
Question from @ReallySmall is this just on Chrome or any browser?

**Comment by marianthi-design** [comment]
Just on Chrome.

**Comment by Matt-Beldon-CDS** [comment]
Unable to reproduce this on chrome version 101.0.4951.67. 
From the users perspective does it appear like the email should have been sent or does it error?

**Comment by marianthi-design** [comment]
It seems to be working now, thanks.

**Comment by Alex-Grubba-CDS** [comment]
Output from Bug Triage session: 

If this is working @marianthi-design please can you close this issue.

**Comment by simplybenuk** [comment]
Closing as no longer an issue
