### ISSUE TITLE
Duplicate user error text

### ISSUE THREAD

**Issue by simplybenuk** [nhsengland/futurenhs#183]
The following text appears when a user tries to register who is already a member of the platform

![image](https://user-images.githubusercontent.com/9471595/169772922-5b49e9c5-a757-45e1-8cbd-ab8ea2e441a0.png)

Should be something like.

A user is already registered with this email address. Please try and [sign in](https://collaborate.future.nhs.uk/members/logon) or [reset your password](https://collaborate.future.nhs.uk/members/forgotpassword) to access FutureNHS

**Comment by Alex-Grubba-CDS** [comment]
MVC issue - Registration work should resolve this, and other known language string errors.

**Comment by marianthi-design** [comment]
Test: @richarddabin

**Comment by simplybenuk** [comment]
Closed as this was an MVC forum related problem
