### ISSUE TITLE
My profile page not working

### ISSUE THREAD

**Issue by simplybenuk** [nhsengland/futurenhs#208]
When I log in
And I select My Profile
I get the following message

"The FutureNHS website is currently experiencing technical difficulties.
We are working to resolve these issues. Please try again later. Thank you for your patience.

Thank you for your patience."

I am logged in as a platform admin

**Comment by Alex-Grubba-CDS** [comment]
@simplybenuk Have you performed any profile edits to this user profile before this error occurred? 

Concern is there has been no code changed here, and we're unable to replicate in other environments. 

Curious if it's a data issue, so we can attempt to recreate.

**Comment by simplybenuk** [comment]
@Alex-Grubba-CDS My actions before this broke were 

I uploaded my profile pic and pronouns which worked fine. I then discovered that only I could see them and I couldn't see them on other people's profiles. As a platform admin I then grabbed another user's ID and went to my profile and swapped in their profile in the URL. This showed me their profile image and pronouns. I then logged out and tried to do exactly the same with a member account and that is when the error occurred and it has not been back since

**Comment by Matt-Beldon-CDS** [comment]
Two issues here: 
First issue is that a members endpoint hasn't been implemented yet, so when an non-admin tries to view another profile it will call the `UpdateMember` endpoint and throw an error as that user does not have the correct permissions to perform that action.
The second issue is on the frontend, if an error happens such as the one above, that page will be broken for every call, regardless whether that call is successful or not

**Comment by Alex-Grubba-CDS** [comment]
@simplybenuk - Can you confirm the first issue has been resolved? Second issue is logged as a bug in ADO, but needs fleshing out by Rich.

**Comment by simplybenuk** [comment]
@Alex-Grubba-CDS yep, closed this
